### ISSUE TITLE
[Feat | Chore] Bump walk-sync; Add pass-through of options to walk-sync

### ISSUE THREAD

**Issue by zimmi88** [stefanpenner/tree-sync#19]
New feature request | Maintenance Chore

**What?**
Bump walk-sync to pick up latest features. Then, provide the ability to pass options through to walk-sync, so we can opt to selectively include or omit files and folders from tree syncing.

**Why?**
- Some use cases might call for omitting or selectively picking directories to sync. Notably, this can help solve an issue where running tree-sync on a folder with a symlink to a parent directory can result in an infinite loop (that eventually crashes when the filename gets too long) by opting to omit the symlinked dir (if the use case allows for it). (https://github.com/joliss/node-walk-sync/issues/30)
- Brings dependency up to date.

_(FYI: I'm already working on this at present - posting an issue ahead of a PR for visibility and feedback. Barring any objections I'll have an PR posted for review soon... ish. Thanks for considering!)_

**Comment by stefanpenner** [comment]
@zimmi88 I would also gladly accept a cycle-breaking PR to address joliss/node-walk-sync#30

Abstractly Maybe something like:

```
let visited = new Set();
if (visited.has('potential path')) { // skip; }
```

**Comment by zimmi88** [comment]
@stefanpenner Thanks for the feedback! (And sorry for the delayed response - I was AFK for a few days.)

I'll take a look at updating node-walk-sync when I get some time and see if this is doable.

**Comment by stefanpenner** [comment]
@zimmi88 👍
