### ISSUE TITLE
Copied files do not get their timestamps updated

### ISSUE THREAD

**Issue by danielgindi** [stefanpenner/tree-sync#22]
Hi!

This package is amazing, with all its dependencies.
There's one thing that's missing, and probably a bug - the synced files do not get their timestamps modified after being written.
The outcome will be that if you run the same sync operation again - they will be re-written.

You need to call `Fs.utimes` on it to update the timestamps.

**Comment by stefanpenner** [comment]
Interesting, yes that isn't expected.

**Comment by stefanpenner** [comment]
@danielgindi's pr https://github.com/stefanpenner/tree-sync/pull/23
